# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseDate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 360))
        Dialog.setMaximumSize(QtCore.QSize(300, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblNumberPeople = QtWidgets.QLabel(Dialog)
        self.lblNumberPeople.setObjectName("lblNumberPeople")
        self.horizontalLayout.addWidget(self.lblNumberPeople)
        self.spinNumberPeople = QtWidgets.QSpinBox(Dialog)
        self.spinNumberPeople.setMinimum(1)
        self.spinNumberPeople.setMaximum(20)
        self.spinNumberPeople.setObjectName("spinNumberPeople")
        self.horizontalLayout.addWidget(self.spinNumberPeople, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Elegir Dia"))
        self.lblNumberPeople.setText(_translate("Dialog", "Numero de personas"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Lunes"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "Martes"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "Miercoles"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "Jueves"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "Viernes"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "Sábado"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "Domingo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Comida"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Cena"))
